# Global config and can be use as namespace
root_dir: ../experiments
dataset: CelebA
trainer: sing
model: dcgan
optim: Adam
gpu: true
n_gpu_use: 1
ngf: 64
ndf: 64
# Data input
batch_size: 32 # 8000
input_size: [ 3, 32, 32 ]
n_epoch: 1000

# Start hparam
z_dim: 64
critic_dim: 64
# Sinkhorn params
scaling: 0.95
ent_reg_loss: 100
ent_reg_cons: 1
sinkhorn_p: 2
sinkhorn_generator_jko_steps: 20
sinkhorn_generator_eta: 1
# Stop hparam

#  lr_scheduler
# lr_scheduler: ExponentialLR
# gamma_lr_scheduler: 0.99
# Note will be as name folder
note: dcgan_sing
# will Create root_dir/dataset/trainer/model/note

---
# Session Modules
DataLoader:
  modules:
    - name: main
      module: {{ dataset }}DataLoader
      configs:
        size: {{ input_size }}
        batch_size: {{ batch_size }}
        crop_size: 160
        shuffle: true
        sampler: ~
        batch_sampler: ~
        num_workers: 2  # default 4
        collate_fn: ~
        pin_memory: false
        drop_last: false
        timeout: 0
        worker_init_fn: ~
Model:
  modules:
    - name: critic
      network:
        module: {{ model }}.Critic
        configs:
          ndf: {{ ndf }}
          z_dim: {{ z_dim }}
          input_size: {{ input_size }}
          critic_dim: {{ critic_dim }}
          reg: {{ sinkhorn_eps }}
          R: {{ R }}
          num_random_samples: 10
      optim:
        module: {{ optim }}
        configs:
          lr: 0.001
          betas: [ 0.5, 0.999 ]
          amsgrad: true
    - name: generator
      network:
        module: {{ model }}.Generator
        configs:
          ngf: {{ ngf }}
          z_dim: {{ z_dim }}
          input_size: {{ input_size }}
          critic_dim: {{ critic_dim }}
      optim:
        module: {{ optim }}
        configs:
          lr: 0.001
          betas: [ 0.5, 0.999 ]
          amsgrad: false
Logger:
  modules:
    - module: Scalar
    - module: Histogram
Evaluator:
  modules:
    - module: GeneratedImage
      configs:
        run_per: [ 10, generator ]
        total_data: 64
        z_dim: {{ z_dim }}
    # - module: CosineSimilarity
    #   configs:
    #     run_per: [1000, generator]
    #     total_data: 64
    #     z_dim: {{ z_dim }}
    # - module: MsSsim
    #   configs:
    #     run_per: [1000, generator]
    #     total_data: 64
    #     z_dim: {{ z_dim }}
#    - module: IS
#      configs:
#        run_per: [1000, generator]
#        total_data: 15000
#        batch_size: 20
#    - module: FID
#      configs:
#        run_per: [1000, generator]
#        total_data: 15000
#        batch_size: 20

Trainer:
  configs:
    save_model_per: [ 10000, generator ] # can select epoch or step
    save_log_per: [ 20, step ] # can select epoch or step
  updater:
    module: {{ trainer }}.GAN
    configs:
      z_dim: {{ z_dim }}
      fixed: false
  modules:
    - name: critic
      criterion:
        module: {{ trainer }}.Critic
        configs:
          scaling: {{ scaling }}
          ent_reg_loss: {{ ent_reg_loss }}
          ent_reg_cons: {{ ent_reg_cons }}
          p: {{ sinkhorn_p }}

    - name: generator
      criterion:
        module: {{ trainer }}.Generator
        configs:
          scaling: {{ scaling }}
          ent_reg_loss: {{ ent_reg_loss }}
          ent_reg_cons: {{ ent_reg_cons }}
          p: {{ sinkhorn_p }}
          jko_steps: {{ sinkhorn_generator_jko_steps }}
          eta: {{ sinkhorn_generator_eta }}